### ISSUE TITLE
 项目下缺少manifest.json文件

### ISSUE THREAD

**Issue by ydCrazy** [ttk-cli/uni-vue3-vite-ts-pinia#26]

**Comment by Allen-1998** [comment]
可以提供详细一些的说明吗

**Comment by ydCrazy** [comment]
重新识别下项目类型就好了，

**Comment by Allen-1998** [comment]
好的，没有问题的话这个讨论就关闭了

**Comment by ydCrazy** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月9日(星期二) 晚上11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ttk-cli/uni-vue3-vite-ts-pinia]  项目下缺少manifest.json文件 (Issue #26)





 
好的，没有问题的话这个讨论就关闭了
