### ISSUE TITLE
项目拉取npm安装之后运行报错

### ISSUE THREAD

**Issue by mlzk** [ttk-cli/uni-vue3-vite-ts-pinia#28]
编译器版本：3.4.6（vue3）
vite v2.9.5

运行到android12  模拟器

报错信息1：
`
Browserslist: caniuse-lite is outdated. Please run:
10:44:03.434   npx browserslist@latest --update-db
10:44:03.442   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
`

报错信息2：
`
 [plugin:vite:load-fallback] Could not load /__uno.css (imported by src/main.ts): ENOENT: no such file or directory, open 'D:\__uno.css'
`
**表现为只有tabs；**

uniapp-cli 升级到最新的正式版 3.0.0-3061820230117001
npm i 之后报错
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: uni-preset-vue@0.0.4
npm ERR! Found: @dcloudio/types@2.5.17
npm ERR! node_modules/@dcloudio/types
npm ERR!   dev @dcloudio/types@"2.5.17" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @dcloudio/types@"^3.0.20" from @dcloudio/uni-app@3.0.0-3061820230117001
npm ERR! node_modules/@dcloudio/uni-app
npm ERR!   @dcloudio/uni-app@"3.0.0-3061820230117001" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\PF37EXR8\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PF37EXR8\AppData\Local\npm-cache\_logs\2023-02-21T02_47_09_258Z-debug-0.log`

之后 `npm i --legacy-peer-deps`
报错
`
10:53:14.919 failed to load config from D:\temp-storage\uni-vue3-vite-ts-pinia\vite.config.ts
10:53:14.919 error during build:
10:53:14.927 TypeError: vite.createFilter is not a function
10:53:14.934     at vuePlugin (D:\temp-storage\uni-vue3-vite-ts-pinia\node_modules\@vitejs\plugin-vue\dist\index.cjs:2601:23)
10:53:14.935     at createPluginVueInstance (D:\temp-storage\uni-vue3-vite-ts-pinia\node_modules\@dcloudio\vite-plugin-uni\dist\vue\options.js:17:12)
10:53:14.949     at uniPlugin (D:\temp-storage\uni-vue3-vite-ts-pinia\node_modules\@dcloudio\vite-plugin-uni\dist\index.js:80:55)
10:53:14.950     at Object.<anonymous> (D:\temp-storage\uni-vue3-vite-ts-pinia\vite.config.ts:94:40)
10:53:14.963     at Module._compile (node:internal/modules/cjs/loader:1165:14)
10:53:14.967     at Object.require.extensions.<computed> [as .ts] (D:\temp-storage\uni-vue3-vite-ts-pinia\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:61679:20)
10:53:14.979     at Module.load (node:internal/modules/cjs/loader:1043:32)
10:53:14.980     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
10:53:14.990     at Module.require (node:internal/modules/cjs/loader:1067:19)
10:53:14.991     at require (node:internal/modules/cjs/helpers:103:18)

`
升级vite
.2.9.5 > 3.2.4

运行报错

`
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->
 at useStore2 (app-service.js:1658:15)
 at useStore (app-service.js:1812:43)
 at  (app-service.js:1818:29)
 at  (app-service.js:2127:3)
`
救命啊老铁~

**Comment by Allen-1998** [comment]
感谢你的反馈，看了一下应该是编译器版本更新导致的向下不兼容问题，晚点我会更新一下项目中整体的依赖版本，或者你也可以先按照最新版本的自己搭建一个项目试试看，本项目实际上主要是为了提供一种搭建项目时整体的结构～

**Comment by Allen-1998** [comment]
依赖已整体升级，可以重新拉取试试看～
