### ISSUE TITLE
使用pinia-auto-refs插件后stroe里的actions发送请求会报错

### ISSUE THREAD

**Issue by tender001** [ttk-cli/uni-vue3-vite-ts-pinia#29]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/12458462/222444205-25730505-f866-4953-80a2-2e97e0c1e746.png">
注释await apiTest.getTest({ a: 1 }) 就不会报错  初步定位到是request.ts里执行了getCommonParams()导致。具体是什么原因？
<img width="569" alt="image" src="https://user-images.githubusercontent.com/12458462/222444815-d793669e-ef78-4b91-b30d-3b096505f982.png">

**Comment by Allen-1998** [comment]
应该是uniapp依赖更新导致的兼容问题，项目整体依赖已更新，可以重新拉取试试看～

**Comment by weiveFf** [comment]
我先拉取最新的代码 这里还是会报错
