### ISSUE TITLE
根据pages.json自动生成页面

### ISSUE THREAD

**Issue by Rosethorn99** [ttk-cli/uni-vue3-vite-ts-pinia#31]
这个addPage文件, 是怎么使用的, 使用node ./auto/addPage.ts运行, 报语法错误.

**Comment by Allen-1998** [comment]
参见 https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/blob/main/package.json#L44 ，执行 npm run add 即可

**Comment by Rosethorn99** [comment]
执行npm run add会出现这个错误, 
![image](https://user-images.githubusercontent.com/40927708/231334578-65e886f0-9320-4f55-8414-2fd5b87f413a.png)

**Comment by Allen-1998** [comment]
感谢指正，应该是事前在做依赖升级的时候无意间将脚本里的 require 改为了 import 导入，已修复 https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/commit/5d8b55f347695cc8da7a7e6ac7063b0bc157d2de ，拉取最新代码即可
