### ISSUE TITLE
微信小程序运行出错

### ISSUE THREAD

**Issue by icooooler** [ttk-cli/uni-vue3-vite-ts-pinia#32]
微信小程序开发过程中app.wxss文件内会编译出*星号css选择器，导致运行时候报错

[自动热重载错误 WXSS 文件编译错误] ./app.wxss
 unexpected token "*"

**Comment by Allen-1998** [comment]
在 FAQ 中有说明哦
[链接](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/blob/main/FAQ.md?plain=1#L51-L59)

**Comment by Nick955** [comment]
https://zhuanlan.zhihu.com/p/581957200 这里有解决办法，unocss做个兼容就好了
