### ISSUE TITLE
[bug] 使用defineProps及withDefaults后，props为空对象的问题

### ISSUE THREAD

**Issue by Nick955** [ttk-cli/uni-vue3-vite-ts-pinia#33]
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/49111166/4d91b131-4bd4-4261-9ca8-0660671c2b00)

想在组件中拿到props里的变量，只能通过getCurrentInstance获取到vue实例，在实例上获取。

无法通过自定义变量的形式获取，请问怎么解决

**Comment by Nick955** [comment]
这就是vue3 setup的语法啊 https://cn.vuejs.org/api/sfc-script-setup.html#defineprops-defineemits
我的意思是我在其他vue3的项目里声明的props变量不会是空对象，不需要通过getCurrentInstance来获取props。
换句话说就是直接console
props.a是undefined，但是getCurrentInstance().props.a 就是 123

**Comment by Allen-1998** [comment]
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/73213399/e077b009-c0da-453f-850e-3cb18bbde756)

我这边是正常的，你的写法和我这里有什么区别吗

**Comment by Nick955** [comment]
谢谢回答，又测试了下发现，声明了默认值的组件如果没有父组件引入，在js里直接获取props里的值就是undefined，但如果有组件引用了，就能正常输出。不太清楚为啥会这样
<img width="1680" alt="image" src="https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/49111166/03feb133-5810-4721-b32c-b1b439db4dc4">

同时也去测试了非uniapp的正常项目，没有这一特殊现象
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/49111166/66f2e35e-7645-4cf5-9b08-127f7c88c038)

**Comment by Allen-1998** [comment]
正常场景下，如果是一个组件，那么必定应该有地方引入才会被挂载，如果是一个页面，那么不应该使用 props，你这边是有什么特殊的业务场景，导致需要这样的写法吗
没被引用会显示 undefind 的原因，大概率是因为小程序的生命周期，渲染，挂载顺序之类的原因导致的，如非必要的话，建议还是不要这样去写
