### ISSUE TITLE
关于打包微信小程序运行报错 [ WXSS 文件编译错误] ./app.wxss unexpected token "*"问题

### ISSUE THREAD

**Issue by wobushirunning** [ttk-cli/uni-vue3-vite-ts-pinia#35]
打包微信小程序运行报错 [ WXSS 文件编译错误] ./app.wxss unexpected token "*"，此问题可以通过在unocss.config.ts中设置theme: {preflightRoot: ['page,::before,::after']}来解决，同时由于小程序不支持 \ \: \[ \$ \. [等转义类名,bg-#81ecec例如这种，同样会在运行时报错，可使用unocss-preset-weapp解决小程序不兼容的相关问题.

**Comment by wobushirunning** [comment]
配置如下：
<img width="1076" alt="image" src="https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/23057289/8aa5db75-a8a1-4b66-8f9d-3afde98de3e5">

**Comment by Allen-1998** [comment]
感谢分享，晚点我会验证一下

**Comment by jocstech** [comment]
这个问题一定要优化解决，uni的主要优势就是可以编译小程序。

**Comment by Allen-1998** [comment]
关于解决小程序不兼容unocss语法的问题，目前看下来社区解决方案比较不错的有两个插件 [unocss-applet](https://github.com/unocss-applet/unocss-applet) [unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp), 由于无法确定社区项目的稳定性，是否会长期维护，所以个人觉得还是不要过早将它集成到此模版会好一些，后期如果可以有一个库维护的比较不错，被 unocss 集成到 core 或者推荐的话，再集成进来会比较合适，当然如果你想在自己的项目中使用的话也是没问题的，我觉得这两个插件都做的很不错

编译wxss报错的问题已修复进主分支，再次感谢分享！
