### ISSUE TITLE
cz校验

### ISSUE THREAD

**Issue by oliver-xie666** [ttk-cli/uni-vue3-vite-ts-pinia#37]
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/75602879/27720745-6cf9-4003-b543-56c8bb8de756)
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/75602879/4f088dc0-6d91-4fcd-a2b3-f0f9cc3d9222)
选不到 scope和CustomScopes是为什么

**Comment by Allen-1998** [comment]
需要先在此文件中添加scopes相关配置，下面是一个参考:
```js
  // 默认生效的scopes选项
  scopes: [
    { name: 'scope1', description: 'Description for scope1' },
    { name: 'scope2', description: 'Description for scope2' },
  ],
  scopeOverrides: {
    // 当type选中 feat 时生效的scopes选项
    feat: [
      { name: 'scope11', description: 'Description for scope11' },
      { name: 'scope22', description: 'Description for scope22' },
    ]
  },
```
