### ISSUE TITLE
好好检查你的依赖有没有夹私货吧 安装依赖太慢了

### ISSUE THREAD

**Issue by CherishMvp** [ttk-cli/uni-vue3-vite-ts-pinia#39]
<img width="1315" alt="image" src="https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/88085841/f3a0b76b-c3a8-49ad-a3e7-473aea6f3bdc">
其他模板的项目都不会像你这么卡拉依赖，梯子也挂了，也换了国内源，死活有问题，pnpm安装

**Comment by Allen-1998** [comment]
1. [.npmrc](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/blob/main/.npmrc) 和 [.nvmrc](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/blob/main/.nvmrc) 中包含了安装依赖相关的配置
