### ISSUE TITLE
无法打包APP，不管是传统打包还是安心打包

### ISSUE THREAD

**Issue by emako** [ttk-cli/uni-vue3-vite-ts-pinia#48]
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/24737061/c51dbd06-0c4d-4599-9c1c-f123a8d19ce0)

HX的版本与仓库里依赖的一致

一直卡在40%，后台显示编译成功，就一直卡主这里了。
不知道大家有没有试过打包APP？

![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/24737061/cd34b4c0-bffa-410d-a97e-cd7049421a8d)

**Comment by warmthsea** [comment]
![Uploading image.png…]()
是的，同样的问题

**Comment by warmthsea** [comment]
是的，同样的问题，无法打包成 apk

![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/45450994/d2fa0428-b8ec-481b-964f-9f86b5ebef9e)

**Comment by warmthsea** [comment]
scripts 命令只支持打成 H5 包

**Comment by warmthsea** [comment]
@Allen-1998 
作者在么，愿意有偿解决此问题

**Comment by warmthsea** [comment]
https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/blob/main/vite.config.ts
https://github.com/Allen-1998/pinia-auto-refs/blob/main/src/index.ts

作者的 pinia-auto-refs 插件库引起的 Android 打包编译卡在那里，应该是APK编译过程中 fs 读文件死锁了
删除掉 vite.config.ts 的 pinia-auto-refs 就能正常编译打包

**Comment by Allen-1998** [comment]
疑似是由于在 pinia-auto-refs@0.0.5 版本中为了解决在 uniapp 开发中的 hmr 问题，将监听文件的更新实现由 handleHotUpdate 替换为了 chokidar，然后在 uniapp 打包时 chokidar 未被释放导致的, 会在 pinia-auto-refs 的新版本中修复，计划修复方案：
区分开发模式和打包模式，仅开发模式启用 chokidar 监听文件变更

**Comment by Allen-1998** [comment]
已修复，升级pinia-auto-refs@0.0.10即可
