### ISSUE TITLE
基础请求封装中某个单词拼写错误

### ISSUE THREAD

**Issue by Lgowen** [ttk-cli/uni-vue3-vite-ts-pinia#50]
源码src/utils/request.ts中的baseRequest方法
<img width="532" alt="image" src="https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/62790161/12c2274f-838b-4f9d-ad1e-568192bb2f07">
有几处拼写错误
responseDate应该是responseData吧
请问一下如何提pr呢

**Comment by Allen-1998** [comment]
感谢指正，下面是chatgpt的回答，可以参考一下😜

Pull Request (PR) 是协作开发中常用的一种方式，特别是在使用 GitHub 进行代码托管时。下面是一个简化的 GitHub 提交 Pull Request 的流程：

1. **Fork 项目：**
   - 在 GitHub 上找到要贡献的项目。
   - 点击页面右上角的 "Fork" 按钮，将该项目复制到你的 GitHub 账户下。

2. **克隆项目到本地：**
   - 在你的 GitHub 账户下找到刚才 Fork 的项目。
   - 点击绿色的 "Code" 按钮，复制项目的 URL。
   - 打开终端，运行 `git clone <项目URL>` 克隆项目到本地。

3. **创建分支：**
   - 进入项目文件夹：`cd 项目文件夹`
   - 创建并切换到一个新的分支，以进行你的修改：
     ```bash
     git checkout -b 你的分支名
     ```

4. **进行修改：**
   - 在本地分支上进行你的修改。添加、修改或删除代码。

5. **提交修改：**
   - 将你的修改添加到暂存区：
     ```bash
     git add .
     ```
   - 提交修改到本地仓库：
     ```bash
     git commit -m "你的提交信息"
     ```

6. **推送到远程仓库：**
   - 将你的分支推送到你的 GitHub 仓库：
     ```bash
     git push origin 你的分支名
     ```

7. **创建 Pull Request：**
   - 在你的 GitHub 仓库页面上，点击 "Compare & pull request" 按钮。
   - 填写 Pull Request 的相关信息，描述你的修改。
   - 点击 "Create pull request" 按钮。

8. **等待审核：**
   - 项目维护者会收到你的 Pull Request，他们将会审查你的修改并提供反馈。
   - 可能需要进行一些额外的修改，以满足项目维护者的要求。

9. **合并 Pull Request：**
   - 一旦审核通过，项目维护者可以选择合并你的 Pull Request。
   - 一旦合并，你的修改将被应用到原始项目中。

10. **更新本地仓库：**
    - 一旦你的 Pull Request 被合并，你需要更新你的本地仓库以包含最新的变更。
      ```bash
      git checkout main  # 切换回主分支（或其他主分支的名称）
      git pull origin main  # 拉取最新的代码
      ```

这是一个基本的流程，具体的步骤可能会有所不同，具体取决于项目的要求和开发团队的工作流程。确保阅读项目的贡献指南，以了解项目特定的要求。
