### ISSUE TITLE
怎么通过package.json的执行命令来更改 /config/env.ts 中的apiEnv的值？

### ISSUE THREAD

**Issue by lx812833** [ttk-cli/uni-vue3-vite-ts-pinia#55]
目前 const apiEnv: ApiEnv = "dev"; 是写死的。那怎么通过package.json的执行命令来更改 /config/env.ts 中的apiEnv的值？来判断是开发还是线上环境？

**Comment by Allen-1998** [comment]
可以参考 https://vitejs.dev/guide/env-and-mode.html#env-files
不过我个人会觉得小程序这种项目，直接在代码里修改环境会比较方便，不需要restart server

**Comment by sendking** [comment]
添加env文件
1. 编辑成小程序无法读取env内的变量
2. 编辑成h5可以读取env的变量
